// <auto-generated />
using System;
using FigureProj.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FigureProj.Infrastructure.Migrations
{
    [DbContext(typeof(FigureContext))]
    [Migration("20251223004448_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FigureProj.Infrastructure.Models.CollectionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Collections_Name");

                    b.ToTable("Collections", (string)null);
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.FigureMetadataModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("FigureId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastModified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id");

                    b.HasIndex("FigureId")
                        .IsUnique();

                    b.ToTable("FigureMetadata", (string)null);
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.FigureModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Area")
                        .HasColumnType("double precision");

                    b.Property<int?>("CollectionId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("Perimeter")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CollectionId");

                    b.HasIndex("Color")
                        .HasDatabaseName("IX_Figures_Color");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_Figures_CreatedAt");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Figures_Name");

                    b.ToTable("Figures", (string)null);

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.FigureTagModel", b =>
                {
                    b.Property<int>("FigureId")
                        .HasColumnType("integer");

                    b.Property<int>("TagId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("FigureId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("FigureTags", (string)null);
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.TagModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Tags_Name_Unique");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.CircleModel", b =>
                {
                    b.HasBaseType("FigureProj.Infrastructure.Models.FigureModel");

                    b.Property<double>("Radius")
                        .HasColumnType("double precision");

                    b.ToTable("Circles", (string)null);
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.RectangleModel", b =>
                {
                    b.HasBaseType("FigureProj.Infrastructure.Models.FigureModel");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<double>("Width")
                        .HasColumnType("double precision");

                    b.ToTable("Rectangles", (string)null);
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.SquareModel", b =>
                {
                    b.HasBaseType("FigureProj.Infrastructure.Models.FigureModel");

                    b.Property<double>("Side")
                        .HasColumnType("double precision");

                    b.ToTable("Squares", (string)null);
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.TriangleModel", b =>
                {
                    b.HasBaseType("FigureProj.Infrastructure.Models.FigureModel");

                    b.Property<double>("A")
                        .HasColumnType("double precision");

                    b.Property<double>("B")
                        .HasColumnType("double precision");

                    b.Property<double>("C")
                        .HasColumnType("double precision");

                    b.ToTable("Triangles", (string)null);
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.FigureMetadataModel", b =>
                {
                    b.HasOne("FigureProj.Infrastructure.Models.FigureModel", "Figure")
                        .WithOne("Metadata")
                        .HasForeignKey("FigureProj.Infrastructure.Models.FigureMetadataModel", "FigureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Figure");
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.FigureModel", b =>
                {
                    b.HasOne("FigureProj.Infrastructure.Models.CollectionModel", "Collection")
                        .WithMany("Figures")
                        .HasForeignKey("CollectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Collection");
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.FigureTagModel", b =>
                {
                    b.HasOne("FigureProj.Infrastructure.Models.FigureModel", "Figure")
                        .WithMany("FigureTags")
                        .HasForeignKey("FigureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FigureProj.Infrastructure.Models.TagModel", "Tag")
                        .WithMany("FigureTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Figure");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.CircleModel", b =>
                {
                    b.HasOne("FigureProj.Infrastructure.Models.FigureModel", null)
                        .WithOne()
                        .HasForeignKey("FigureProj.Infrastructure.Models.CircleModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.RectangleModel", b =>
                {
                    b.HasOne("FigureProj.Infrastructure.Models.FigureModel", null)
                        .WithOne()
                        .HasForeignKey("FigureProj.Infrastructure.Models.RectangleModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.SquareModel", b =>
                {
                    b.HasOne("FigureProj.Infrastructure.Models.FigureModel", null)
                        .WithOne()
                        .HasForeignKey("FigureProj.Infrastructure.Models.SquareModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.TriangleModel", b =>
                {
                    b.HasOne("FigureProj.Infrastructure.Models.FigureModel", null)
                        .WithOne()
                        .HasForeignKey("FigureProj.Infrastructure.Models.TriangleModel", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.CollectionModel", b =>
                {
                    b.Navigation("Figures");
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.FigureModel", b =>
                {
                    b.Navigation("FigureTags");

                    b.Navigation("Metadata");
                });

            modelBuilder.Entity("FigureProj.Infrastructure.Models.TagModel", b =>
                {
                    b.Navigation("FigureTags");
                });
#pragma warning restore 612, 618
        }
    }
}
